version: 2

models:
  - name: calculate_avg_durations
    columns:
      - name: avg_duration
        description: "The avg durations for all tracks in db"
        tests:
          - not_null

  - name: search_songs
    columns:
      - name: id
        description: "The id for the songs with the keywords"
        tests:
          - not_null
  
  - name: keyword_tracks
    columns:
      - name: id
        description: "The id for the songs with top 50 popularity"
        tests:
          - not_null
