name: "song_stars"
version: '1.0.0'
config-version: 2

# Use a custom profile.yml file for database connections
profile: "default"

# Specify the models directory
models:
  search_path: ["models"]
  # Use the `song_stars` schema in the target database
  song_stars:
    # Define the sources to use in the models
    sources:
      - name: tracks
        tables:
          - name: tracks
